#!/usr/bin/env bash
# lib/wizard.sh — Diagnostic wizard, fault localization, and driver advisories.
# Sourced by flap; do not execute directly.

# Module-level report accumulator (replaces the nested report_lines local).
# run_wizard() resets this at entry; _rpt() appends to it.
_REPORT_LINES=()

# _rpt — append a line to the report and echo it to stdout.
# Strips ANSI escapes for the saved report file.
_rpt() {
  local _l="$1"
  echo -e "$_l"
  _REPORT_LINES+=("$(echo -e "$_l" | sed 's/\x1b\[[0-9;]*m//g')")
}

_get_bond_master() {
  local iface="$1"
  # Test hook: _LINK_FLAP_TEST_BOND_MASTERS="eth0=bond0,eth1=bond1"
  if [[ -n "${_LINK_FLAP_TEST_BOND_MASTERS:-}" ]]; then
    local _bm_pair
    IFS=',' read -ra _bm_pairs <<< "$_LINK_FLAP_TEST_BOND_MASTERS"
    for _bm_pair in "${_bm_pairs[@]}"; do
      [[ "$_bm_pair" == "${iface}="* ]] && { echo "${_bm_pair#*=}"; return; }
    done
    return
  fi
  [[ -L "/sys/class/net/${iface}/master" ]] || return 0
  basename "$(readlink -f "/sys/class/net/${iface}/master")" 2>/dev/null || true
}

_wiz_read() {
  local path="$1"
  if [[ -n "${_LINK_FLAP_TEST_WIZARD_DIR:-}" ]]; then
    cat "${_LINK_FLAP_TEST_WIZARD_DIR}/$(basename "$path")" 2>/dev/null || echo ""
  else
    cat "$path" 2>/dev/null || echo ""
  fi
}

_wiz_cmd() {
  local key="$1"; shift
  if [[ -n "${_LINK_FLAP_TEST_WIZARD_DIR:-}" ]]; then
    cat "${_LINK_FLAP_TEST_WIZARD_DIR}/${key}" 2>/dev/null || echo ""
  else
    "$@" 2>/dev/null || echo ""
  fi
}

# Helpers for DUT interface sysfs/command reads (separate mock dir for tests).
_wiz_read_dut() {
  local path="$1"
  if [[ -n "${_LINK_FLAP_TEST_DUT_DIR:-}" ]]; then
    cat "${_LINK_FLAP_TEST_DUT_DIR}/$(basename "$path")" 2>/dev/null || echo ""
  else
    cat "$path" 2>/dev/null || echo ""
  fi
}

_wiz_cmd_dut() {
  local key="$1"; shift
  if [[ -n "${_LINK_FLAP_TEST_DUT_DIR:-}" ]]; then
    cat "${_LINK_FLAP_TEST_DUT_DIR}/${key}" 2>/dev/null || echo ""
  else
    "$@" 2>/dev/null || echo ""
  fi
}

# _drv_advisories DRIVER_NAME DRIVER_VER FIRMWARE_VER IFACE
# Prints zero or more lines: LEVEL<TAB>Title<TAB>Description<TAB>Fix<TAB>SourceURL
# Each line is a known advisory for the given driver, sourced from official documentation.
_drv_advisories() {
  local drv="$1" iface="${4:-IFACE}"
  case "$drv" in
    r8169)
      printf 'WARN\t%s\t%s\t%s\t%s\n' \
        "Driver advisory — r8169 (Realtek)" \
        "r8169 has well-documented EEE negotiation and link-stability issues with many switch vendors. Realtek distributes an alternative out-of-tree driver (r8168) with improved stability." \
        "Disable EEE: ethtool --set-eee ${iface} eee off  — or install r8168 from Realtek" \
        "https://www.realtek.com/en/component/zoo/category/network-interface-controllers-10-100-1000m-gigabit-ethernet-pci-express-software"
      ;;
    tg3)
      printf 'WARN\t%s\t%s\t%s\t%s\n' \
        "Driver advisory — tg3 (Broadcom/Tigon3)" \
        "tg3 EEE (green ethernet) negotiation is documented to cause link drops with certain switch vendors. The kernel tg3 documentation lists EEE as a known interoperability concern." \
        "Disable EEE: ethtool --set-eee ${iface} eee off" \
        "https://www.kernel.org/doc/html/latest/networking/device_drivers/ethernet/broadcom/tg3.html"
      ;;
    virtio_net)
      printf 'INFO\t%s\t%s\t%s\t%s\n' \
        "Driver note — virtio_net (virtual NIC)" \
        "virtio_net link events are generated by the hypervisor. Live VM migrations and hypervisor pause events appear as link flaps and are expected behaviour, not hardware faults." \
        "Check hypervisor migration/event logs for the VM; correlate flap timestamps with migration events" \
        "https://www.qemu.org/docs/master/devel/migration.html"
      ;;
    bnxt_en)
      printf 'WARN\t%s\t%s\t%s\t%s\n' \
        "Driver advisory — bnxt_en (Broadcom NetXtreme)" \
        "Older bnxt_en firmware versions have known link-stability issues. Broadcom provides updated firmware and driver release notes documenting fixed defects per NIC model." \
        "Check current firmware: ethtool -i ${iface}; update from Broadcom support" \
        "https://docs.broadcom.com/"
      ;;
    sfc)
      printf 'WARN\t%s\t%s\t%s\t%s\n' \
        "Driver advisory — sfc (Solarflare/AMD Xilinx)" \
        "Some sfc firmware versions have intermittent link-stability issues triggered by flow-control mismatches. AMD/Xilinx publishes per-firmware-version release notes documenting resolved defects." \
        "Disable flow control: ethtool -A ${iface} autoneg off rx off tx off; update sfc firmware" \
        "https://docs.amd.com/"
      ;;
    cdc_ncm|cdc_ether|cdc_mbim)
      printf 'WARN\t%s\t%s\t%s\t%s\n' \
        "Driver note — ${drv} (USB CDC Ethernet)" \
        "cdc_ncm/cdc_ether/cdc_mbim are USB-attached Ethernet adapters. High RX drop counts are typically caused by USB NCM aggregation limits, URB pool exhaustion, or USB host-controller bandwidth contention — not the Ethernet cable. The firmware-version field reflects the kernel version string, which is normal for this driver. CDC Status OK confirms the USB control channel is healthy; it does not guarantee the data path is drop-free. Swapping the Ethernet cable or switch port will not resolve drops that originate in the USB subsystem." \
        "1. Check NCM parameters: cat /sys/module/cdc_ncm/parameters/*  2. Check USB errors: dmesg | grep -iE 'cdc_ncm|xhci|ehci|usb.*error|usb.*reset'  3. Try a different USB host port (different root hub, not just a different socket on the same hub)  4. Inspect the USB path for intermediate hubs: udevadm info --query=path /sys/class/net/${iface}  5. If drops persist across all USB ports: replace the USB Ethernet adapter itself" \
        "https://www.kernel.org/doc/html/latest/networking/cdc_ncm.html"
      ;;
  esac
}

run_wizard() {
  local iface="$1"
  _REPORT_LINES=()   # reset for this wizard run
  mkdir -p "$BACKUP_DIR" "$REPORT_DIR"

  # 1. Create backup
  local backup_id
  backup_id=$(create_backup "$iface")

  # 2. Validate interface (skipped in test mode)
  if [[ -z "${_LINK_FLAP_TEST_WIZARD_DIR:-}" ]]; then
    if ! ip link show "$iface" &>/dev/null; then
      echo "Error: interface '$iface' not found." >&2; exit 1
    fi
  fi

  # 3. Collect diagnostic data
  local operstate carrier_changes power_control
  local ethtool_out ethtool_s_out ethtool_eee_out dmesg_raw dmesg_out

  operstate=$(_wiz_read "/sys/class/net/${iface}/operstate")
  carrier_changes=$(_wiz_read "/sys/class/net/${iface}/carrier_changes")
  power_control=$(_wiz_cmd power_control cat "/sys/class/net/${iface}/device/power/control")
  ethtool_out=$(_wiz_cmd ethtool ethtool "$iface")
  ethtool_s_out=$(_wiz_cmd ethtool_s ethtool -S "$iface")
  ethtool_eee_out=$(_wiz_cmd ethtool_eee ethtool --show-eee "$iface")
  dmesg_raw=$(_wiz_cmd dmesg dmesg)
  dmesg_out=$(echo "$dmesg_raw" | grep -i "$iface" | tail -30 2>/dev/null || true)

  # Fault localization data
  local ethtool_i_out ip_route_out all_links_out resolv_conf_out
  ethtool_i_out=$(_wiz_cmd ethtool_i ethtool -i "$iface")
  ip_route_out=$(_wiz_cmd ip_route ip route show)
  all_links_out=$(_wiz_cmd all_links ip link show)
  resolv_conf_out=$(_wiz_cmd resolv_conf cat /etc/resolv.conf)

  # DUT interface data (only when --dut is set)
  local dut_carrier_changes="" dut_operstate="" dut_speed=""
  if [[ -n "$DUT_IFACE" ]]; then
    dut_carrier_changes=$(_wiz_read_dut "/sys/class/net/${DUT_IFACE}/carrier_changes")
    dut_operstate=$(_wiz_read_dut "/sys/class/net/${DUT_IFACE}/operstate")
    local dut_ethtool_out
    dut_ethtool_out=$(_wiz_cmd_dut dut_ethtool ethtool "$DUT_IFACE")
    dut_speed=$(echo "$dut_ethtool_out" | grep -i "Speed:" | awk '{print $2}' | head -1 || true)
  fi

  # Bond/LAG membership
  local bond_master="" bond_carrier_changes="" bond_mode=""
  bond_master=$(_get_bond_master "$iface")
  if [[ -n "$bond_master" ]]; then
    if [[ -n "${_LINK_FLAP_TEST_WIZARD_DIR:-}" ]]; then
      bond_carrier_changes=$(cat "${_LINK_FLAP_TEST_WIZARD_DIR}/bond_carrier_changes" 2>/dev/null || true)
      bond_mode=$(cat "${_LINK_FLAP_TEST_WIZARD_DIR}/bond_mode" 2>/dev/null || true)
    else
      bond_carrier_changes=$(cat "/sys/class/net/${bond_master}/carrier_changes" 2>/dev/null || true)
      bond_mode=$(cat "/sys/class/net/${bond_master}/bonding/mode" 2>/dev/null || true)
    fi
  fi

  # node_exporter metrics — uses _NE_METRICS_CACHE (fetch_node_exporter called at Step 3 entry)
  local ne_up ne_rx_err ne_tx_err ne_rx_drop ne_tx_drop ne_tx_packets ne_rx_packets
  ne_up=$(_ne_val node_network_up "$iface")
  ne_rx_err=$(_ne_val node_network_receive_errs_total "$iface")
  ne_tx_err=$(_ne_val node_network_transmit_errs_total "$iface")
  ne_rx_drop=$(_ne_val node_network_receive_drop_total "$iface")
  ne_tx_drop=$(_ne_val node_network_transmit_drop_total "$iface")
  ne_tx_packets=$(_ne_val node_network_transmit_packets_total "$iface")
  ne_rx_packets=$(_ne_val node_network_receive_packets_total "$iface")

  # iperf3 active probe — uses _IPERF3_RESULT_CACHE (run_iperf3 called at Step 3 entry)
  local iperf3_bps iperf3_retransmits
  iperf3_bps=$(_iperf3_val "end.sum_sent.bits_per_second")
  iperf3_retransmits=$(_iperf3_val "end.sum_sent.retransmits")

  local speed duplex autoneg
  speed=$(echo "$ethtool_out" | grep -i "Speed:" | awk '{print $2}' | head -1 || true)
  duplex=$(echo "$ethtool_out" | grep -i "Duplex:" | awk '{print $2}' | head -1 || true)
  autoneg=$(echo "$ethtool_out" | grep -i "Auto-negotiation:" | awk '{print $2}' | head -1 || true)

  # FEC mode (25G+ NICs only)
  local ethtool_fec_out
  ethtool_fec_out=$(_wiz_cmd ethtool_fec ethtool --show-fec "$iface")

  # Pause frame / flow control
  local ethtool_a_out
  # shellcheck disable=SC2034  # ethtool_a_out is collected for fixture availability; pause data is in ethtool_s
  ethtool_a_out=$(_wiz_cmd ethtool_a ethtool -a "$iface")

  # Local MTU
  local local_mtu
  local_mtu=$(_wiz_read "/sys/class/net/${iface}/mtu")

  # SFP DOM (Digital Optical Monitoring) — silent on copper / unsupported NICs
  local dom_out rx_power_dbm="" tx_power_dbm=""
  dom_out=$(_wiz_cmd ethtool_m ethtool -m "$iface")
  if [[ -n "$dom_out" ]]; then
    rx_power_dbm=$(echo "$dom_out" \
      | grep -i "receiver signal\|rx power" \
      | grep -oP '[-]?[0-9]+\.[0-9]+(?= dBm)' \
      | head -1 || true)
    tx_power_dbm=$(echo "$dom_out" \
      | grep -i "laser output power\|tx power" \
      | grep -oP '[-]?[0-9]+\.[0-9]+(?= dBm)' \
      | head -1 || true)
  fi

  # LLDP neighbour — silent if lldpctl not installed
  local lldp_peer_name="" lldp_peer_port="" _lldp_available=0
  if command -v lldpctl &>/dev/null; then
    _lldp_available=1
    local lldp_raw
    lldp_raw=$(_wiz_cmd lldpctl lldpctl "$iface")
    lldp_peer_name=$(echo "$lldp_raw" | awk -F'SysName:' 'NF>1{gsub(/^[ \t]+/,"",$2); print $2; exit}')
    lldp_peer_port=$(echo "$lldp_raw" | awk -F'PortDescr:' 'NF>1{gsub(/^[ \t]+/,"",$2); print $2; exit}')
  fi

  # USB NIC detection — resolve the device symlink; if it passes through a USB bus
  # the interface is USB-attached (cdc_ncm, cdc_ether, asix, etc.).
  # In test mode, the fixture file 'iface_usb_path' overrides the live sysfs lookup.
  local _iface_usb_path="" _iface_is_usb=0
  if [[ -n "${_LINK_FLAP_TEST_WIZARD_DIR:-}" ]]; then
    _iface_usb_path=$(cat "${_LINK_FLAP_TEST_WIZARD_DIR}/iface_usb_path" 2>/dev/null || true)
  elif [[ -L "/sys/class/net/${iface}/device" ]]; then
    _iface_usb_path=$(readlink -f "/sys/class/net/${iface}/device" 2>/dev/null || true)
  fi
  [[ "$_iface_usb_path" == *"/usb"* ]] && _iface_is_usb=1

  # If USB NIC: collect USB kernel events and cdc_ncm module parameters
  local usb_dmesg_out="" ncm_params_out=""
  if [[ "$_iface_is_usb" -eq 1 ]]; then
    usb_dmesg_out=$(_wiz_cmd usb_dmesg \
      sh -c "dmesg | grep -iE 'cdc_ncm|cdc_ether|xhci|ehci|usb.*error|usb.*reset|usb.*disconnect' | tail -30")
    if [[ -d /sys/module/cdc_ncm/parameters ]]; then
      ncm_params_out=$(for _p in /sys/module/cdc_ncm/parameters/*; do
        printf '%s=%s\n' "$(basename "$_p")" "$(cat "$_p" 2>/dev/null)"
      done)
    fi
  fi

  # 4. Build findings array — each entry: "LEVEL<tab>Title<tab>Description<tab>Fix"
  local -a findings=()

  # Carrier instability — two severity tiers
  if [[ -n "$carrier_changes" ]] && [[ "$carrier_changes" =~ ^[0-9]+$ ]]; then
    if [[ "$carrier_changes" -gt 500 ]]; then
      findings+=("CAUSE"$'\t'"Severe carrier instability"$'\t'"${carrier_changes} link state transitions since boot (cumulative). A healthy, stable link has 1–5 total changes across its entire lifetime (initial autoneg + planned reboots). 500+ transitions indicates sustained physical instability: faulty cable, degraded SFP, switch port fault, or NIC hardware failure."$'\t'"Replace cable or SFP; try a different switch port; run: ethtool -d ${iface}")
    elif [[ "$carrier_changes" -gt 20 ]]; then
      findings+=("WARN"$'\t'"Elevated carrier changes since boot"$'\t'"${carrier_changes} link state changes since boot (cumulative). A healthy link typically has 1–5 total changes. More than 20 suggests intermittent instability."$'\t'"Check cable, SFP module, or switch port")
    fi
  fi

  # EEE enabled
  if echo "$ethtool_eee_out" | grep -qi "EEE status: enabled"; then
    findings+=("CAUSE"$'\t'"Energy-Efficient Ethernet (EEE) enabled"$'\t'"EEE allows the NIC to enter low-power states, causing link drops"$'\t'"ethtool --set-eee ${iface} eee off")
  fi

  # NIC power management (runtime PM)
  if [[ "$power_control" == "auto" ]]; then
    findings+=("CAUSE"$'\t'"NIC power management enabled (runtime PM)"$'\t'"Runtime PM (power/control=auto) can suspend the NIC and drop the link"$'\t'"echo 'on' > /sys/class/net/${iface}/device/power/control")
  fi

  # RX CRC errors
  local rx_crc
  rx_crc=$(echo "$ethtool_s_out" | grep -i "rx_crc_errors" | awk '{print $2}' | head -1 || true)
  if [[ -n "$rx_crc" ]] && [[ "$rx_crc" =~ ^[0-9]+$ ]] && [[ "$rx_crc" -gt 0 ]]; then
    findings+=("CAUSE"$'\t'"RX CRC errors detected"$'\t'"${rx_crc} CRC errors — indicates physical layer fault (cable/SFP/switch port)"$'\t'"Replace cable or SFP; check switch port error counters")
  fi

  # Half-duplex
  if echo "$ethtool_out" | grep -qi "Duplex: Half"; then
    findings+=("WARN"$'\t'"Half-duplex detected"$'\t'"Half-duplex causes collisions and link instability at high load"$'\t'"Check switch port autoneg settings; if mismatch: ethtool -s ${iface} duplex full autoneg on")
  fi

  # Speed/duplex unreadable — autoneg failure or link down
  if [[ "${speed:-}" == "Unknown!" || "${speed:-}" == "Unknown" ]]; then
    findings+=("CAUSE"$'\t'"Link speed unreadable — auto-negotiation failure"$'\t'"The NIC reports unknown speed and duplex, meaning it cannot determine link parameters. This usually means the link is physically down, auto-negotiation has completely failed, or the NIC/driver has faulted. Combined with high carrier changes, this is a strong indicator of physical layer failure."$'\t'"Check cable/SFP and switch port autoneg; try: ethtool -s ${iface} autoneg on")
  fi

  # No physical link
  if echo "$ethtool_out" | grep -qi "Link detected: no"; then
    findings+=("CAUSE"$'\t'"No physical link detected"$'\t'"No carrier signal — check cable, SFP, switch port"$'\t'"Verify cable is seated; check switch port status")
  fi

  # dmesg: hardware error / fatal
  if echo "$dmesg_out" | grep -qi "hardware error\|fatal"; then
    findings+=("CAUSE"$'\t'"Hardware error in kernel log"$'\t'"Kernel reported hardware error for ${iface} — possible NIC failure"$'\t'"Check full dmesg: dmesg | grep -i ${iface}")
  fi

  # dmesg: reset / reinit
  if echo "$dmesg_out" | grep -qi "reset\|reinit"; then
    findings+=("WARN"$'\t'"NIC reset/reinit events in kernel log"$'\t'"Kernel log shows NIC resets for ${iface}"$'\t'"Check full dmesg: dmesg | grep -i ${iface}")
  fi

  # node_exporter: RX errors > 0
  if [[ -n "$ne_rx_err" ]] && [[ "$ne_rx_err" =~ ^[0-9]+$ ]] && [[ "$ne_rx_err" -gt 0 ]]; then
    findings+=("WARN"$'\t'"RX errors (node_exporter)"$'\t'"${ne_rx_err} RX errors seen — possible cable or hardware fault"$'\t'"Check cable; run: ethtool -S ${iface} | grep -i error")
  fi

  # node_exporter: TX errors > 0
  if [[ -n "$ne_tx_err" ]] && [[ "$ne_tx_err" =~ ^[0-9]+$ ]] && [[ "$ne_tx_err" -gt 0 ]]; then
    findings+=("WARN"$'\t'"TX errors (node_exporter)"$'\t'"${ne_tx_err} TX errors seen — possible congestion or hardware fault"$'\t'"Check switch port; run: ethtool -S ${iface} | grep -i error")
  fi

  # TX drops — rate-based when packet totals available (>1% = CAUSE, >0.1% = WARN per
  # Prometheus community standard and TCP performance research showing >0.1% loss degrades
  # throughput). Falls back to absolute counts only when NE packet data is unavailable.
  local _tx_drop_cause=0
  if [[ -n "$ne_tx_drop" ]] && [[ "$ne_tx_drop" =~ ^[0-9]+$ ]] && [[ "$ne_tx_drop" -gt 0 ]]; then
    local _tx_drop_fired=0
    if [[ -n "$ne_tx_packets" && "$ne_tx_packets" =~ ^[0-9]+$ && "$ne_tx_packets" -gt 0 ]]; then
      local _tx_drop_rate_pct _tx_drop_rate_int
      _tx_drop_rate_pct=$(awk -v d="$ne_tx_drop" -v p="$ne_tx_packets" \
        'BEGIN{printf "%.4f", d/p*100}')
      _tx_drop_rate_int=$(awk -v v="$_tx_drop_rate_pct" 'BEGIN{printf "%d", v*1000}')
      if [[ "$_tx_drop_rate_int" -gt 1000 ]]; then   # > 1.000%
        findings+=("CAUSE"$'\t'"Severe TX packet loss"$'\t'"${ne_tx_drop} TX drops out of ${ne_tx_packets} packets (${_tx_drop_rate_pct}% loss rate since boot). Loss >1% significantly degrades TCP throughput and indicates ring buffer exhaustion, driver overload, or physical layer instability."$'\t'"Check: ethtool -g ${iface} for ring buffer size; ethtool -S ${iface} | grep -i drop")
        _tx_drop_cause=1; _tx_drop_fired=1
      elif [[ "$_tx_drop_rate_int" -gt 100 ]]; then  # > 0.100%
        findings+=("WARN"$'\t'"Elevated TX packet loss"$'\t'"${ne_tx_drop} TX drops out of ${ne_tx_packets} packets (${_tx_drop_rate_pct}% loss rate since boot). Loss >0.1% measurably degrades TCP throughput."$'\t'"Run: ethtool -S ${iface} | grep -i drop")
        _tx_drop_fired=1
      fi
    fi
    if [[ "$_tx_drop_fired" -eq 0 ]]; then
      # Fallback: packet totals unavailable; absolute counts are traffic-volume-dependent
      if [[ "$ne_tx_drop" -gt 5000 ]]; then
        findings+=("CAUSE"$'\t'"Severe TX drop count"$'\t'"${ne_tx_drop} TX drops (packet total unavailable — rate cannot be computed). Enable node_exporter for rate-based analysis."$'\t'"Check: ethtool -g ${iface} for ring buffer size; ethtool -S ${iface} | grep -i drop")
        _tx_drop_cause=1
      elif [[ "$ne_tx_drop" -gt 100 ]]; then
        findings+=("WARN"$'\t'"Elevated TX drop count"$'\t'"${ne_tx_drop} TX drops (packet total unavailable — significance depends on traffic volume). Enable node_exporter for rate-based analysis."$'\t'"Run: ethtool -S ${iface} | grep -i drop")
      fi
    fi
  fi

  # RX drops — same rate-based approach as TX drops
  if [[ -n "$ne_rx_drop" ]] && [[ "$ne_rx_drop" =~ ^[0-9]+$ ]] && [[ "$ne_rx_drop" -gt 0 ]]; then
    local _rx_drop_fired=0
    if [[ -n "$ne_rx_packets" && "$ne_rx_packets" =~ ^[0-9]+$ && "$ne_rx_packets" -gt 0 ]]; then
      local _rx_drop_rate_pct _rx_drop_rate_int
      _rx_drop_rate_pct=$(awk -v d="$ne_rx_drop" -v p="$ne_rx_packets" \
        'BEGIN{printf "%.4f", d/p*100}')
      _rx_drop_rate_int=$(awk -v v="$_rx_drop_rate_pct" 'BEGIN{printf "%d", v*1000}')
      if [[ "$_rx_drop_rate_int" -gt 1000 ]]; then   # > 1.000%
        findings+=("CAUSE"$'\t'"Severe RX packet loss"$'\t'"${ne_rx_drop} RX drops out of ${ne_rx_packets} packets (${_rx_drop_rate_pct}% loss rate since boot). The receive buffer is discarding a significant fraction of incoming frames. Causes: NIC ring buffer too small, CPU interrupt starvation (/proc/net/softnet_stat time_squeeze), or physical layer instability."$'\t'"Check: ethtool -g ${iface} for ring buffer size; ethtool -K ${iface} gro on; check CPU load with top")
        _rx_drop_fired=1
      elif [[ "$_rx_drop_rate_int" -gt 100 ]]; then  # > 0.100%
        findings+=("WARN"$'\t'"Elevated RX packet loss"$'\t'"${ne_rx_drop} RX drops out of ${ne_rx_packets} packets (${_rx_drop_rate_pct}% loss rate since boot). Loss >0.1% measurably impacts TCP throughput."$'\t'"Run: ethtool -S ${iface} | grep -i drop; ethtool -g ${iface}")
        _rx_drop_fired=1
      fi
    fi
    if [[ "$_rx_drop_fired" -eq 0 ]]; then
      # Fallback: packet totals unavailable
      if [[ "$ne_rx_drop" -gt 5000 ]]; then
        findings+=("CAUSE"$'\t'"Severe RX drop count"$'\t'"${ne_rx_drop} RX drops (packet total unavailable — rate cannot be computed). Enable node_exporter for rate-based analysis."$'\t'"Check: ethtool -g ${iface}; ethtool -K ${iface} gro on")
      elif [[ "$ne_rx_drop" -gt 100 ]]; then
        findings+=("WARN"$'\t'"Elevated RX drop count"$'\t'"${ne_rx_drop} RX drops (packet total unavailable — significance depends on traffic volume). Enable node_exporter for rate-based analysis."$'\t'"Run: ethtool -S ${iface} | grep -i drop; ethtool -g ${iface}")
      fi
    fi
  fi

  # Combined physical-layer failure signature (>= 2 of 3 indicators present).
  # TX drop component uses the _tx_drop_cause flag set by the rate-based analysis above,
  # so the synthesis threshold matches the proven rate threshold, not an arbitrary count.
  local _phys_indicators=0
  [[ "${speed:-}" == "Unknown!" || "${speed:-}" == "Unknown" ]] && \
    (( _phys_indicators++ )) || true
  [[ -n "$carrier_changes" && "$carrier_changes" =~ ^[0-9]+$ && \
     "$carrier_changes" -gt 500 ]] && (( _phys_indicators++ )) || true
  [[ "${_tx_drop_cause}" -eq 1 ]] && (( _phys_indicators++ )) || true
  if (( _phys_indicators >= 2 )); then
    local -a _phys_parts=()
    [[ "${speed:-}" == "Unknown!" || "${speed:-}" == "Unknown" ]] && \
      _phys_parts+=("unknown speed negotiation")
    [[ -n "$carrier_changes" && "$carrier_changes" =~ ^[0-9]+$ && \
       "$carrier_changes" -gt 500 ]] && \
      _phys_parts+=("severe carrier instability (${carrier_changes} transitions)")
    [[ "${_tx_drop_cause}" -eq 1 ]] && \
      _phys_parts+=("significant TX packet loss")
    local _phys_desc
    _phys_desc=$(IFS=', '; echo "${_phys_parts[*]}")
    findings+=("CAUSE"$'\t'"Physical layer failure signature"$'\t'"Multiple indicators point to a physical layer fault: ${_phys_desc}. This combination is characteristic of a damaged cable, failed SFP transceiver, or faulty switch port."$'\t'"1. Replace the patch cable  2. Try a different switch port  3. If SFP: swap the transceiver  4. Run: ethtool -d ${iface} for NIC register dump")
  fi

  # iperf3: TCP retransmits > 0
  if [[ -n "$iperf3_retransmits" ]] && [[ "$iperf3_retransmits" =~ ^[0-9]+$ ]] && \
     [[ "$iperf3_retransmits" -gt 0 ]]; then
    findings+=("WARN"$'\t'"TCP retransmits during iperf3 test"$'\t'"${iperf3_retransmits} retransmits in 5s test to ${IPERF3_SERVER} — congestion or packet loss"$'\t'"Test longer: iperf3 -c ${IPERF3_SERVER} -t 30; check switch port buffers")
  fi

  # Known driver advisories (sourced from official vendor/kernel documentation)
  local _adv_drv_name _adv_drv_ver _adv_drv_fw
  _adv_drv_name=$(echo "$ethtool_i_out" | grep "^driver:"           | awk '{print $2}' | head -1 || true)
  _adv_drv_ver=$(echo  "$ethtool_i_out" | grep "^version:"          | awk '{print $2}' | head -1 || true)
  _adv_drv_fw=$(echo   "$ethtool_i_out" | grep "^firmware-version:" | awk '{print $2}' | head -1 || true)
  if [[ -n "$_adv_drv_name" ]]; then
    while IFS=$'\t' read -r adv_level adv_title adv_desc adv_fix adv_src; do
      [[ -z "$adv_level" ]] && continue
      findings+=("${adv_level}"$'\t'"${adv_title}"$'\t'"${adv_desc}"$'\t'"${adv_fix}  |  See: ${adv_src}")
    done < <(_drv_advisories "$_adv_drv_name" "$_adv_drv_ver" "$_adv_drv_fw" "$iface")
  fi

  # USB NIC — high RX drops with a stable link strongly implicate the USB subsystem
  # rather than the Ethernet cable.  Only add these findings when we know it's USB.
  if [[ "$_iface_is_usb" -eq 1 ]]; then
    if [[ -n "$ne_rx_drop" && "$ne_rx_drop" =~ ^[0-9]+$ && "$ne_rx_drop" -gt 100 ]]; then
      local _cc="${carrier_changes:-0}"
      if [[ "$_cc" =~ ^[0-9]+$ && "$_cc" -lt 20 ]]; then
        findings+=("WARN"$'\t'"USB NIC: high RX drops with stable link"$'\t'"${ne_rx_drop} RX drops on ${_adv_drv_name:-cdc_ncm} with only ${_cc} carrier changes. A stable link and high drop count on a USB Ethernet adapter strongly suggests a USB-side issue — NCM aggregation limits, URB pool exhaustion, or USB host-controller bandwidth contention — rather than an Ethernet cable or switch port fault. Swapping the Ethernet cable and switch port will not resolve drops that originate in the USB subsystem."$'\t'"Check: dmesg | grep -iE 'cdc_ncm|xhci|usb.*reset'; try a different USB root-hub port; replace the USB adapter if drops persist")
      fi
    fi
    if [[ "${speed:-}" == "Unknown!" || "${speed:-}" == "Unknown" ]]; then
      findings+=("INFO"$'\t'"USB NIC: Unknown speed is a driver limitation, not autoneg failure"$'\t'"Many USB CDC Ethernet adapters (${_adv_drv_name:-cdc_ncm}) do not expose link speed via ethtool. An Unknown speed result does not indicate cable or autoneg failure — it is a known limitation of USB NIC drivers. Use ip link show ${iface} to confirm the interface is UP/LOWER_UP."$'\t'"ip link show ${iface}")
    fi
  fi

  # Bond/LAG member findings
  if [[ -n "$bond_master" ]]; then
    local _bond_mode_label=""
    [[ -n "$bond_mode" ]] && _bond_mode_label=" (mode: ${bond_mode})"
    if [[ -n "$bond_carrier_changes" && "$bond_carrier_changes" =~ ^[0-9]+$ && \
          -n "$carrier_changes" && "$carrier_changes" =~ ^[0-9]+$ ]] && \
       (( carrier_changes > bond_carrier_changes * 3 && carrier_changes > 10 )); then
      findings+=("WARN"$'\t'"Bond member instability"$'\t'"${iface} is a member of ${bond_master}${_bond_mode_label}. Member carrier changes (${carrier_changes}) vastly exceed the bond (${bond_carrier_changes}), indicating this member link is the problem — not the overall bond."$'\t'"Check cable/SFP on ${iface}; consider removing from ${bond_master} for isolation: ip link set ${iface} nomaster")
    else
      findings+=("INFO"$'\t'"Bond member of ${bond_master}"$'\t'"${iface} is a member of ${bond_master}${_bond_mode_label}. Bond carrier changes: ${bond_carrier_changes:-unknown}."$'\t'"Review bond status: cat /proc/net/bonding/${bond_master}")
    fi
  fi

  # MTU mismatch (local vs LLDP peer)
  if [[ -n "$local_mtu" && "$local_mtu" =~ ^[0-9]+$ ]]; then
    local lldp_raw_full
    lldp_raw_full=$(_wiz_cmd lldpctl lldpctl "$iface")
    local peer_mtu
    peer_mtu=$(echo "$lldp_raw_full" | grep -i "Maximum Frame Size:" \
      | grep -oP '[0-9]+' | head -1 || true)
    if [[ -n "$peer_mtu" && "$peer_mtu" =~ ^[0-9]+$ ]] && \
       [[ "$local_mtu" -ne "$peer_mtu" ]]; then
      findings+=("WARN"$'\t'"MTU mismatch (local ${local_mtu} vs peer ${peer_mtu})"$'\t'"Local MTU is ${local_mtu} but LLDP peer advertises Maximum Frame Size ${peer_mtu}. Mismatched MTUs cause silent packet drops for frames exceeding the smaller value."$'\t'"Align MTUs: ip link set ${iface} mtu ${peer_mtu}; or adjust the switch port MTU")
    fi
  fi

  # Autonegotiation mismatch (local vs link partner)
  local peer_autoneg
  peer_autoneg=$(echo "$ethtool_out" | grep -i "Link partner advertised auto-negotiation:" \
    | awk '{print $NF}' | head -1 || true)
  if [[ -n "$peer_autoneg" && -n "$autoneg" ]]; then
    if [[ "$autoneg" == "on" && "$peer_autoneg" == "No" ]] || \
       [[ "$autoneg" == "off" && "$peer_autoneg" == "Yes" ]]; then
      findings+=("WARN"$'\t'"Autonegotiation mismatch (local=${autoneg}, peer=${peer_autoneg})"$'\t'"Local autoneg is ${autoneg} but link partner advertises ${peer_autoneg}. Autoneg mismatches cause speed/duplex negotiation failures and link instability."$'\t'"Align autoneg: ethtool -s ${iface} autoneg on; or match the switch port setting")
    fi
  fi

  # FEC mode check (25G+ NICs only)
  local speed_int
  speed_int=$(echo "${speed:-}" | grep -oP '[0-9]+' | head -1 || true)
  if [[ -n "$speed_int" && "$speed_int" =~ ^[0-9]+$ && "$speed_int" -ge 25000 ]]; then
    local active_fec
    active_fec=$(echo "$ethtool_fec_out" | grep -i "Active FEC" \
      | awk -F: '{gsub(/^[ \t]+/,"",$2); print $2}' | head -1 || true)
    if [[ -n "$active_fec" ]] && echo "$active_fec" | grep -qiE "Off|None|Not reported"; then
      findings+=("WARN"$'\t'"FEC disabled on ${speed} link"$'\t'"Forward Error Correction is off (Active FEC: ${active_fec}) on a ${speed} link. 25G+ links have tighter signal margins and typically require FEC (Reed-Solomon or BaseR) for reliable operation."$'\t'"Enable FEC: ethtool --set-fec ${iface} encoding rs; or encoding baser")
    fi
  fi

  # Pause frame / flow control
  local rx_pause tx_pause
  rx_pause=$(echo "$ethtool_s_out" | grep -i "rx_pause" \
    | grep -oP '[0-9]+' | head -1 || true)
  tx_pause=$(echo "$ethtool_s_out" | grep -i "tx_pause" \
    | grep -oP '[0-9]+' | head -1 || true)
  if [[ -n "$rx_pause" && "$rx_pause" =~ ^[0-9]+$ && "$rx_pause" -gt 1000 ]] || \
     [[ -n "$tx_pause" && "$tx_pause" =~ ^[0-9]+$ && "$tx_pause" -gt 1000 ]]; then
    findings+=("WARN"$'\t'"Excessive pause frames"$'\t'"rx_pause=${rx_pause:-0}, tx_pause=${tx_pause:-0}. High pause frame counts indicate flow control congestion between this NIC and the switch. Sustained pause frames can trigger carrier drops on some NICs."$'\t'"Review flow control: ethtool -a ${iface}; disable if not needed: ethtool -A ${iface} rx off tx off")
  fi

  # Duplex mismatch (local full, peer half)
  local peer_duplex
  peer_duplex=$(echo "$ethtool_out" | grep -i "Link partner.*Duplex:" \
    | awk '{print $NF}' | head -1 || true)
  if [[ -z "$peer_duplex" ]]; then
    peer_duplex=$(echo "$ethtool_out" | grep -i "Link partner advertised" \
      | grep -oi "Half" | head -1 || true)
  fi
  if [[ "${duplex:-}" == "Full" && "$peer_duplex" == "Half" ]]; then
    findings+=("CAUSE"$'\t'"Duplex mismatch (local Full, peer Half)"$'\t'"This NIC is running Full duplex but the link partner is advertising Half duplex. A duplex mismatch is a classic cause of link flapping: the full-duplex side interprets the half-duplex side's deference as a link fault."$'\t'"Set both ends to autoneg: ethtool -s ${iface} autoneg on; or force both to full duplex on the switch")
  fi

  # 5. Historical system load at flap time (Prometheus, if configured)
  if [[ -n "$PROM_URL" || -n "${_LINK_FLAP_TEST_PROM:-}" ]]; then
    local _wiz_first_epoch=""
    if [[ -f "$TMPFILE" ]]; then
      _wiz_first_epoch=$(awk -v ifc="$iface" '$2==ifc {print $1; exit}' "$TMPFILE" 2>/dev/null || true)
    fi
    if [[ -n "$_wiz_first_epoch" ]]; then
      local _wiz_cpu _wiz_mem
      _wiz_cpu=$(prom_query_at \
        'avg(rate(node_cpu_seconds_total{mode="idle"}[5m]))*100' "$_wiz_first_epoch")
      _wiz_mem=$(prom_query_at \
        'node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes*100' "$_wiz_first_epoch")
      if [[ -n "$_wiz_cpu" ]]; then
        local _wiz_cpu_int
        _wiz_cpu_int=$(printf "%.0f" "$_wiz_cpu")
        if (( _wiz_cpu_int < 15 )); then
          findings+=("CAUSE"$'\t'"CPU saturation at flap time"$'\t'"CPU idle was ${_wiz_cpu_int}% when flapping began — system was heavily loaded. Under this level of saturation the kernel's NAPI softirq budget can be exhausted before the NIC ring buffer drains, causing packet loss and link instability. Direct evidence of softirq starvation is visible in /proc/net/softnet_stat (column 9: time_squeeze)."$'\t'"Investigate with: top -b -n1 | head -20; also check: awk '{print \$10}' /proc/net/softnet_stat")
        elif (( _wiz_cpu_int < 30 )); then
          findings+=("WARN"$'\t'"High CPU load at flap time"$'\t'"CPU idle was ${_wiz_cpu_int}% when flapping began — elevated load can delay NIC interrupt processing and increase softirq latency. Check /proc/net/softnet_stat (column 9: time_squeeze) for direct evidence."$'\t'"Check: top, htop; also: awk '{print \$10}' /proc/net/softnet_stat")
        fi
      fi
      if [[ -n "$_wiz_mem" ]]; then
        local _wiz_mem_int
        _wiz_mem_int=$(printf "%.0f" "$_wiz_mem")
        if (( _wiz_mem_int < 10 )); then
          findings+=("WARN"$'\t'"Low memory at flap time"$'\t'"Only ${_wiz_mem_int}% memory was available when flapping began — memory pressure can cause driver buffer exhaustion"$'\t'"Check: free -h; consider adding swap or reducing memory consumers")
        fi
      fi
    fi
  fi

  # 6. Pattern analysis — use TMPFILE events for the interface
  local -a iface_events=()
  if [[ -f "$TMPFILE" ]]; then
    mapfile -t iface_events < <(grep -F -- " ${iface} " "$TMPFILE" | sort -n 2>/dev/null || true)
  fi
  local event_count=${#iface_events[@]}
  findings+=("INFO"$'\t'"Flap events in scan window"$'\t'"${event_count} link event(s) found in the last ${WINDOW_MINUTES}m window"$'\t'"Use -v to see individual events")

  if [[ $event_count -ge 4 ]]; then
    local -a epochs=()
    local evt
    for evt in "${iface_events[@]}"; do
      epochs+=("$(echo "$evt" | awk '{print $1}')")
    done
    local i max_interval=0 min_interval=999999 spread=0
    for (( i=1; i<${#epochs[@]}; i++ )); do
      local interval=$(( epochs[i] - epochs[i-1] ))
      [[ $interval -gt $max_interval ]] && max_interval=$interval
      [[ $interval -lt $min_interval ]] && min_interval=$interval
    done
    spread=$(( max_interval - min_interval ))
    # Spread < 30 s across all inter-event gaps means events are evenly spaced.
    # Even spacing suggests a timer-driven cause: STP hello/TCN, LACP PDU, or power-management cycle.
    if [[ $spread -lt 30 ]]; then
      findings+=("WARN"$'\t'"Regular flap interval detected"$'\t'"Inter-event intervals are consistent (spread ${spread}s) — may indicate STP, LACP, or power-cycle timer"$'\t'"Check STP: bridge link; check LACP: teamdctl; check power management")
    fi
  fi

  # 6. Print report (terminal + capture via _rpt → _REPORT_LINES)
  local ts_now; ts_now=$(date "+%Y-%m-%d %H:%M:%S")
  local SEP="════════════════════════════════════════════════════════════"

  _rpt ""
  if [[ -n "${_LINK_FLAP_TEST_WIZARD_DIR:-}" ]]; then
    _rpt "${YELLOW}${BOLD}  !! SYNTHETIC TEST DATA — wizard sysfs/commands are mocked, not real hardware !!${RESET}"
    _rpt ""
  fi
  _rpt "${BOLD}${SEP}${RESET}"
  _rpt "${BOLD}  Diagnostic Report — ${iface}${RESET}"
  _rpt "  Generated : ${ts_now}"
  _rpt "  Backup ID : ${backup_id}"
  _rpt "${BOLD}${SEP}${RESET}"
  _rpt ""
  _rpt "${BOLD}Interface State${RESET}"
  _rpt "  operstate      : ${operstate:-unknown}"

  # carrier_changes with severity hint
  local _cc_hint=""
  if [[ -n "$carrier_changes" && "$carrier_changes" =~ ^[0-9]+$ ]]; then
    if   (( carrier_changes > 500 )); then _cc_hint="  [SEVERE — each change = 1 link drop+restore]"
    elif (( carrier_changes > 20  )); then _cc_hint="  [elevated — stable links expect < 5]"
    else                                   _cc_hint="  [normal]"
    fi
  fi
  _rpt "  carrier_changes: ${carrier_changes:-unknown}${_cc_hint}"

  # speed with hint when unreadable
  local _speed_hint=""
  [[ "${speed:-}" == "Unknown!" || "${speed:-}" == "Unknown" ]] && \
    _speed_hint="  [unreadable — autoneg failed or link down]" || true
  _rpt "  speed          : ${speed:-unknown}${_speed_hint}"

  # duplex with hint
  local _duplex_hint=""
  [[ "${duplex:-}" == "Half" ]] && _duplex_hint="  [collision risk at high load]" || true
  [[ "${duplex:-}" == "Unknown" || "${duplex:-}" == "Unknown!" ]] && \
    _duplex_hint="  [unreadable — same cause as unknown speed]" || true
  _rpt "  duplex         : ${duplex:-unknown}${_duplex_hint}"

  _rpt "  autoneg        : ${autoneg:-unknown}"
  _rpt "  power/control  : ${power_control:-unknown}"
  if [[ -n "$_NE_METRICS_CACHE" ]]; then
    local ne_state_str=""
    if [[ "$ne_up" == "1" ]]; then
      ne_state_str="UP"
    elif [[ "$ne_up" == "0" ]]; then
      ne_state_str="DOWN"
    fi
    _rpt ""
    _rpt "${BOLD}node_exporter Metrics${RESET}"
    if [[ -n "$ne_state_str" ]]; then _rpt "  link state     : ${ne_state_str}"; fi
    if [[ -n "$ne_rx_err"    ]]; then _rpt "  RX errors      : ${ne_rx_err} total"; fi
    if [[ -n "$ne_tx_err"    ]]; then _rpt "  TX errors      : ${ne_tx_err} total"; fi
    if [[ -n "$ne_rx_drop"   ]]; then _rpt "  RX drops       : ${ne_rx_drop} total"; fi
    if [[ -n "$ne_tx_drop"   ]]; then _rpt "  TX drops       : ${ne_tx_drop} total"; fi
  fi
  if [[ -n "$_IPERF3_RESULT_CACHE" ]]; then
    local mbps_str="?"
    if [[ -n "$iperf3_bps" ]]; then
      mbps_str=$(python3 -c "import sys; print(f'{float(sys.argv[1])/1e6:.1f}')" "$iperf3_bps" 2>/dev/null || echo "?")
    fi
    _rpt ""
    if [[ -n "$_IPERF3_BIND_IP" ]]; then
      _rpt "${BOLD}iperf3 Results${RESET}  (→ ${IPERF3_SERVER} via ${_IPERF3_BIND_IP})"
    else
      _rpt "${BOLD}iperf3 Results${RESET}  (→ ${IPERF3_SERVER}, unbound)"
    fi
    _rpt "  bandwidth      : ${mbps_str} Mbps"
    if [[ -n "$iperf3_retransmits" ]]; then _rpt "  retransmits    : ${iperf3_retransmits}"; fi
  fi
  _rpt ""
  _rpt "${BOLD}Findings${RESET}"

  local cause_count=0 warn_count=0
  local finding idx

  # Pass 1 — at-a-glance summary table
  _rpt ""
  _rpt "  ${DIM}#  Level   Title${RESET}"
  _rpt "  ${DIM}─  ──────  ───────────────────────────────────────────────────────${RESET}"
  idx=0
  for finding in "${findings[@]}"; do
    local f_level f_title f_desc f_fix
    IFS=$'\t' read -r f_level f_title f_desc f_fix <<< "$finding"
    (( idx++ )) || true
    case "$f_level" in
      CAUSE) _rpt "  ${idx}  ${RED}CAUSE${RESET}   ${f_title}" ;;
      WARN)  _rpt "  ${idx}  ${YELLOW}WARN${RESET}    ${f_title}" ;;
      INFO)  _rpt "  ${idx}  ${CYAN}INFO${RESET}    ${f_title}" ;;
    esac
  done

  # Pass 2 — detailed blocks
  _rpt ""
  _rpt "  ${DIM}── Details ────────────────────────────────────────────────────${RESET}"
  idx=0
  for finding in "${findings[@]}"; do
    local f_level f_title f_desc f_fix
    IFS=$'\t' read -r f_level f_title f_desc f_fix <<< "$finding"
    (( idx++ )) || true
    _rpt ""
    case "$f_level" in
      CAUSE)
        _rpt "  [${idx}] ${RED}[CAUSE]${RESET} ${BOLD}${f_title}${RESET}"
        _rpt "      ${f_desc}"
        _rpt "      ${GREEN}[FIX]${RESET}  ${f_fix}"
        (( cause_count++ )) || true
        ;;
      WARN)
        _rpt "  [${idx}] ${YELLOW}[WARN]${RESET}  ${BOLD}${f_title}${RESET}"
        _rpt "      ${f_desc}"
        _rpt "      ${GREEN}[FIX]${RESET}  ${f_fix}"
        (( warn_count++ )) || true
        ;;
      INFO)
        _rpt "  [${idx}] ${CYAN}[INFO]${RESET}  ${f_title}: ${f_desc}"
        ;;
    esac
  done

  # ── Auto-apply fixes (--fix) ───────────────────────────────────────────────
  # A fix is "auto-applicable" if it is a single shell command (no numbered steps,
  # no pipes, no semicolons). Only CAUSE and WARN findings are considered.
  if [[ "$FIX_MODE" -eq 1 ]]; then
    local _fix_applied=0 _fix_failed=0 _fix_skipped=0
    idx=0
    for finding in "${findings[@]}"; do
      local f_level f_title f_desc f_fix
      IFS=$'\t' read -r f_level f_title f_desc f_fix <<< "$finding"
      (( idx++ )) || true
      [[ "$f_level" == "INFO" ]] && continue
      [[ -z "$f_fix" ]] && continue
      # Skip multi-step instructions (numbered lists, pipes, semicolons)
      [[ "$f_fix" =~ ^[0-9]+\. ]] && continue
      [[ "$f_fix" == *"|"* ]] && continue
      [[ "$f_fix" == *";"* ]] && continue
      # Skip non-actionable advice (starts with "Check:", "Review ", etc.)
      [[ "$f_fix" =~ ^(Check|Review|Investigate|See|Replace|Try) ]] && continue

      _rpt ""
      if [[ -t 0 ]] && [[ -z "${_LINK_FLAP_TEST_FIX_LOG:-}" ]]; then
        # Interactive: prompt
        _rpt "  ${GREEN}[FIX ${idx}]${RESET} ${f_fix}"
        read -rp "  Apply this fix now? [y/N] " _fix_answer < /dev/tty
        if [[ "$_fix_answer" =~ ^[Yy] ]]; then
          if eval "$f_fix" 2>/dev/null; then
            _rpt "  ${GREEN}[APPLIED]${RESET} ${f_title}"
            (( _fix_applied++ )) || true
          else
            _rpt "  ${RED}[FAILED]${RESET}  ${f_title} — try with sudo: sudo $f_fix"
            (( _fix_failed++ )) || true
          fi
        else
          (( _fix_skipped++ )) || true
        fi
      elif [[ -n "${_LINK_FLAP_TEST_FIX_LOG:-}" ]]; then
        # Test mode: log commands to file
        echo "$f_fix" >> "$_LINK_FLAP_TEST_FIX_LOG"
        _rpt "  ${GREEN}[APPLIED]${RESET} ${f_title}"
        (( _fix_applied++ )) || true
      else
        # Non-interactive: print command only
        _rpt "  ${DIM}[--fix]${RESET} To apply: ${f_fix}"
      fi
    done
    if [[ $(( _fix_applied + _fix_failed + _fix_skipped )) -gt 0 ]]; then
      _rpt ""
      _rpt "  Fixes: ${_fix_applied} applied, ${_fix_failed} failed, ${_fix_skipped} skipped"
    fi
  fi

  _rpt ""
  _rpt "${BOLD}Summary${RESET}"
  _rpt "  Causes  : ${cause_count}"
  _rpt "  Warnings: ${warn_count}"
  _rpt "  Report  : ${REPORT_DIR}/${backup_id}.txt"
  _rpt "  Rollback: ./flap -r ${backup_id}"
  _rpt "  Verify  : ./flap -i ${iface} -w 10  (after applying fix)"
  _rpt ""

  # 7. Fault localization section — pass data via associative array nameref
  declare -A _DIAG_DATA=(
    [iface]="$iface"
    [ethtool_i_out]="$ethtool_i_out"
    [ethtool_out]="$ethtool_out"
    [ip_route_out]="$ip_route_out"
    [all_links_out]="$all_links_out"
    [resolv_conf_out]="$resolv_conf_out"
    [dmesg_out]="$dmesg_out"
    [carrier_changes]="${carrier_changes:-}"
    [speed]="${speed:-}"
    [rx_crc]="${rx_crc:-}"
    [ne_tx_drop]="${ne_tx_drop:-}"
    [dut_carrier_changes]="${dut_carrier_changes:-}"
    [dut_operstate]="${dut_operstate:-}"
    [dut_speed]="${dut_speed:-}"
    [tx_drop_cause]="${_tx_drop_cause:-0}"
    [rx_power_dbm]="${rx_power_dbm:-}"
    [tx_power_dbm]="${tx_power_dbm:-}"
    [lldp_peer_name]="${lldp_peer_name:-}"
    [lldp_peer_port]="${lldp_peer_port:-}"
    [lldp_available]="${_lldp_available:-0}"
    [iface_is_usb]="${_iface_is_usb:-0}"
    [iface_usb_path]="${_iface_usb_path:-}"
    [adv_drv_name]="${_adv_drv_name:-}"
    [usb_dmesg_out]="${usb_dmesg_out:-}"
    [ncm_params_out]="${ncm_params_out:-}"
  )
  run_fault_localization _DIAG_DATA

  # 8. Save report (ANSI already stripped by _rpt)
  printf '%s\n' "${_REPORT_LINES[@]}" > "${REPORT_DIR}/${backup_id}.txt"
}

# ── Fault Localization ────────────────────────────────────────────────────────
# Layer-by-layer fault isolation appended to the wizard report.
# Accepts a single argument: the name of an associative array (Bash 4.3+ nameref).
run_fault_localization() {
  local -n _d=$1
  local iface="${_d[iface]}"
  local ethtool_i_out="${_d[ethtool_i_out]}"
  local ethtool_out="${_d[ethtool_out]}"
  local ip_route_out="${_d[ip_route_out]}"
  local all_links_out="${_d[all_links_out]}"
  local resolv_conf_out="${_d[resolv_conf_out]}"
  local dmesg_out="${_d[dmesg_out]}"
  local carrier_changes="${_d[carrier_changes]}"
  local speed="${_d[speed]}"
  local rx_crc="${_d[rx_crc]}"
  local ne_tx_drop="${_d[ne_tx_drop]}"
  local dut_carrier_changes="${_d[dut_carrier_changes]}"
  local dut_operstate="${_d[dut_operstate]}"
  local dut_speed="${_d[dut_speed]}"
  local tx_drop_cause="${_d[tx_drop_cause]:-0}"
  local rx_power_dbm="${_d[rx_power_dbm]}"
  local tx_power_dbm="${_d[tx_power_dbm]}"
  local lldp_peer_name="${_d[lldp_peer_name]}"
  local lldp_peer_port="${_d[lldp_peer_port]}"
  local lldp_available="${_d[lldp_available]:-0}"
  local _iface_is_usb="${_d[iface_is_usb]:-0}"
  local _iface_usb_path="${_d[iface_usb_path]}"
  local _adv_drv_name="${_d[adv_drv_name]}"
  local usb_dmesg_out="${_d[usb_dmesg_out]}"
  local ncm_params_out="${_d[ncm_params_out]}"

  local SEP="════════════════════════════════════════════════════════════"

  _rpt ""
  _rpt "${BOLD}${SEP}${RESET}"
  _rpt "${BOLD}  Fault Localization — ${iface}${RESET}"
  _rpt "${BOLD}${SEP}${RESET}"
  _rpt ""

  # ── Layer 1: Physical (cable / connector / SFP) ───────────────────────────
  local l1_status="OK"
  local -a l1_evidence=()
  if [[ "${speed:-}" == "Unknown!" || "${speed:-}" == "Unknown" ]]; then
    if [[ "$_iface_is_usb" -eq 1 ]]; then
      # USB NICs commonly report Unknown speed — this is a driver limitation, not autoneg failure.
      l1_evidence+=("Unknown speed (expected ${_adv_drv_name:-USB NIC} driver limitation — not an autoneg fault)")
    else
      l1_status="SUSPECT"; l1_evidence+=("Unknown speed (autoneg failed)")
    fi
  fi
  if [[ -n "$carrier_changes" && "$carrier_changes" =~ ^[0-9]+$ && \
        "$carrier_changes" -gt 500 ]]; then
    l1_status="SUSPECT"; l1_evidence+=("${carrier_changes} carrier changes (severe)")
  fi
  if [[ -n "$rx_crc" && "$rx_crc" =~ ^[0-9]+$ && "$rx_crc" -gt 0 ]]; then
    l1_status="SUSPECT"; l1_evidence+=("RX CRC errors (${rx_crc})")
  fi
  echo "$ethtool_out" | grep -qi "Link detected: no" && \
    l1_status="SUSPECT" && l1_evidence+=("No physical link detected")
  # tx_drop_cause is set by run_wizard's rate-based analysis (>1% loss rate or >5000 absolute fallback)
  if [[ "${tx_drop_cause}" -eq 1 ]]; then
    l1_status="SUSPECT"; l1_evidence+=("Severe TX packet loss (${ne_tx_drop} drops)")
  fi

  # 6. SFP DOM — RX optical power (signal arriving from the remote end)
  #    Low RX power implicates the remote SFP, fibre attenuation, or dirty connectors.
  #    Typical thresholds: warn < -30 dBm, critical < -35 dBm
  if [[ -n "$rx_power_dbm" ]]; then
    if awk "BEGIN{exit !($rx_power_dbm < -35)}"; then
      l1_status="SUSPECT"
      l1_evidence+=("RX optical power ${rx_power_dbm} dBm — remote SFP or fibre degraded")
    elif awk "BEGIN{exit !($rx_power_dbm < -30)}"; then
      l1_evidence+=("RX optical power ${rx_power_dbm} dBm (marginal; monitor)")
    fi
  fi

  # 7. SFP DOM — TX optical power (local laser health; most SFPs rated -9 dBm minimum)
  if [[ -n "$tx_power_dbm" ]]; then
    if awk "BEGIN{exit !($tx_power_dbm < -9)}"; then
      l1_status="SUSPECT"
      l1_evidence+=("TX optical power ${tx_power_dbm} dBm — local SFP laser degraded")
    fi
  fi

  # 8. LLDP neighbour — remote device visibility
  local lldp_note=""
  if [[ -n "$lldp_peer_name" ]]; then
    lldp_note="${lldp_peer_name}${lldp_peer_port:+ port $lldp_peer_port}"
  elif [[ "$lldp_available" -eq 1 ]]; then
    # lldpctl present but no neighbour on an up link is suspicious
    echo "$ethtool_out" | grep -qi "Link detected: yes" && \
      l1_evidence+=("No LLDP neighbour on an up link — remote port may be down or misconfigured")
  fi

  local l1_col="$GREEN"
  [[ "$l1_status" == "SUSPECT" ]] && l1_col="$RED"
  _rpt "  Layer 1 — Physical (cable / connector / SFP)"
  _rpt "    Status   : ${l1_col}${l1_status}${RESET}"
  [[ -n "$lldp_note" ]] && _rpt "    Remote   : ${lldp_note}"
  if [[ "${#l1_evidence[@]}" -gt 0 ]]; then
    _rpt "    Evidence : $(IFS='; '; echo "${l1_evidence[*]}")"
    if echo "${l1_evidence[*]}" | grep -qi "remote\|LLDP"; then
      _rpt "    Next step: Investigate remote device/port${lldp_note:+ ($lldp_note)}; check far-end SFP and fibre connectors"
    elif [[ "$_iface_is_usb" -eq 1 ]]; then
      _rpt "    Next step: Cable+port already swapped → the USB adapter, USB cable, or USB host controller is suspect"
    else
      _rpt "    Next step: Replace cable; try a different switch port; swap SFP"
    fi
  fi
  if [[ "$_iface_is_usb" -eq 1 ]]; then
    _rpt "    USB path : ${_iface_usb_path:-unknown}"
    if [[ -n "$ncm_params_out" ]]; then
      _rpt "    NCM params:"
      while IFS= read -r _p; do
        _rpt "               ${_p}"
      done <<< "$ncm_params_out"
    fi
    if [[ -n "$usb_dmesg_out" ]]; then
      _rpt "    USB events (recent dmesg):"
      while IFS= read -r _u; do
        _rpt "               ${_u}"
      done <<< "$usb_dmesg_out"
    fi
  fi
  _rpt ""

  # ── Layer 2: NIC Driver ───────────────────────────────────────────────────
  local drv_name drv_ver drv_fw
  drv_name=$(echo "$ethtool_i_out" | grep "^driver:"   | awk '{print $2}' | head -1 || true)
  drv_ver=$(echo  "$ethtool_i_out" | grep "^version:"  | awk '{print $2}' | head -1 || true)
  drv_fw=$(echo   "$ethtool_i_out" | grep "^firmware-version:" | awk '{print $2}' | head -1 || true)

  local l2drv_status="OK"
  [[ -z "$drv_name" ]] && l2drv_status="UNKNOWN"
  echo "$dmesg_out" | grep -qi "reset\|reinit" && l2drv_status="SUSPECT"
  echo "$dmesg_out" | grep -qi "firmware.*fail\|failed to load firmware" && l2drv_status="SUSPECT"
  # Severe TX drops with stable carrier_changes → driver queue issue, not physical
  # Uses tx_drop_cause flag (rate-based CAUSE level) to avoid arbitrary absolute threshold
  if [[ "${tx_drop_cause}" -eq 1 && \
        -n "$carrier_changes" && "$carrier_changes" =~ ^[0-9]+$ && "$carrier_changes" -lt 5 ]]; then
    l2drv_status="SUSPECT"
  fi

  local l2drv_col="$GREEN"
  [[ "$l2drv_status" == "SUSPECT" ]] && l2drv_col="$RED"
  [[ "$l2drv_status" == "UNKNOWN" ]] && l2drv_col="$DIM"
  _rpt "  Layer 2 — NIC Driver"
  _rpt "    Status   : ${l2drv_col}${l2drv_status}${RESET}"
  if [[ -n "$drv_name" ]]; then
    local drv_line="    Driver   : ${drv_name}"
    [[ -n "$drv_ver" ]] && drv_line+="  v${drv_ver}"
    [[ -n "$drv_fw"  ]] && drv_line+="  fw ${drv_fw}"
    _rpt "$drv_line"
    while IFS=$'\t' read -r adv_level adv_title adv_desc adv_fix adv_src; do
      [[ -z "$adv_level" ]] && continue
      local adv_col="$YELLOW"
      [[ "$adv_level" == "INFO" ]] && adv_col="$CYAN"
      _rpt "    Advisory : ${adv_col}${adv_title}${RESET}"
      _rpt "               ${adv_desc}"
      [[ -n "$adv_src" ]] && _rpt "               ${DIM}See: ${adv_src}${RESET}"
    done < <(_drv_advisories "$drv_name" "$drv_ver" "$drv_fw" "$iface")
  else
    _rpt "    Driver   : (ethtool -i not available)"
  fi
  _rpt ""

  # ── Layer 2: Switch Port ──────────────────────────────────────────────────
  local l2sw_status="UNKNOWN"
  local -a l2sw_evidence=()
  echo "$ethtool_out" | grep -qi "Duplex: Half" && \
    l2sw_status="SUSPECT" && l2sw_evidence+=("Half-duplex — autoneg mismatch with switch")
  # STP changes detected would also be a switch indicator, but that's PCAP-only

  local l2sw_col="$DIM"
  [[ "$l2sw_status" == "SUSPECT" ]] && l2sw_col="$RED"
  _rpt "  Layer 2 — Switch Port"
  _rpt "    Status   : ${l2sw_col}${l2sw_status}${RESET}"
  if [[ "${#l2sw_evidence[@]}" -gt 0 ]]; then
    _rpt "    Evidence : $(IFS='; '; echo "${l2sw_evidence[*]}")"
  else
    _rpt "    Note     : LLDP not available; no STP topology changes seen"
  fi
  _rpt "    Next step: Check switch port error counters; try a different port"
  _rpt ""

  # ── Layer 3: Gateway / Router ─────────────────────────────────────────────
  local gateway
  gateway=$(echo "$ip_route_out" | awk '/^default via/{print $3; exit}' || true)

  local l3_status="UNKNOWN"
  local l3_gw_line="" l3_inet_line=""
  if [[ -n "$gateway" ]]; then
    local ping_gw_out
    ping_gw_out=$(_wiz_cmd ping_gw ping -c 1 -W 2 "$gateway")
    if echo "$ping_gw_out" | grep -q "1 received\|1 packets received"; then
      l3_status="OK"
      local rtt
      rtt=$(echo "$ping_gw_out" | grep -oP 'time=\K[0-9.]+' | head -1 || true)
      l3_gw_line="    Gateway  : ${gateway}  (reachable${rtt:+, ${rtt}ms})"
    else
      l3_status="SUSPECT"
      l3_gw_line="    Gateway  : ${gateway}  (UNREACHABLE — check router/cable to gateway)"
    fi
    # Internet reachability (only if gateway OK)
    if [[ "$l3_status" == "OK" ]]; then
      local ping_inet_out
      ping_inet_out=$(_wiz_cmd ping_inet ping -c 1 -W 2 8.8.8.8)
      if echo "$ping_inet_out" | grep -q "1 received\|1 packets received"; then
        l3_inet_line="    Internet : reachable (8.8.8.8)"
      else
        l3_inet_line="    Internet : UNREACHABLE (gateway OK but no internet — check router/ISP)"
      fi
    fi
  else
    l3_gw_line="    Gateway  : not configured (no default route)"
  fi

  local l3_col="$GREEN"
  [[ "$l3_status" == "SUSPECT" ]] && l3_col="$RED"
  [[ "$l3_status" == "UNKNOWN" ]] && l3_col="$DIM"
  _rpt "  Layer 3 — Gateway / Router"
  _rpt "    Status   : ${l3_col}${l3_status}${RESET}"
  [[ -n "$l3_gw_line"   ]] && _rpt "$l3_gw_line"
  [[ -n "$l3_inet_line" ]] && _rpt "$l3_inet_line"
  _rpt ""

  # ── VPN ──────────────────────────────────────────────────────────────────
  local vpn_iface
  vpn_iface=$(echo "$all_links_out" | grep -oP '(?<=\d: )(tun|tap|wg|vpn|tailscale)\w*' | head -1 || true)
  _rpt "  VPN"
  if [[ -n "$vpn_iface" ]]; then
    local vpn_route
    vpn_route=$(echo "$ip_route_out" | grep "$vpn_iface" | head -1 || true)
    _rpt "    Status   : ${YELLOW}Detected${RESET} (${vpn_iface})"
    [[ -n "$vpn_route" ]] && _rpt "    Route    : ${vpn_route}"
    _rpt "    Note     : Check VPN tunnel stability if routing issues are suspected"
  else
    _rpt "    Status   : ${DIM}Not detected${RESET}"
  fi
  _rpt ""

  # ── DNS ───────────────────────────────────────────────────────────────────
  local nameserver
  nameserver=$(echo "$resolv_conf_out" | awk '/^nameserver/{print $2; exit}' || true)
  local dns_status="UNKNOWN"
  if [[ -n "$nameserver" ]]; then
    local dig_out
    dig_out=$(_wiz_cmd dig_dns dig +short +time=2 +tries=1 google.com "@${nameserver}")
    if [[ -n "$dig_out" ]]; then
      dns_status="OK"
    else
      dns_status="SUSPECT"
    fi
  fi

  local dns_col="$GREEN"
  [[ "$dns_status" == "SUSPECT" ]] && dns_col="$RED"
  [[ "$dns_status" == "UNKNOWN" ]] && dns_col="$DIM"
  _rpt "  DNS"
  _rpt "    Status   : ${dns_col}${dns_status}${RESET}"
  if [[ -n "$nameserver" ]]; then
    _rpt "    Resolver : ${nameserver}${dns_status:+  (google.com ${dns_status,,})}"
  else
    _rpt "    Resolver : not configured (/etc/resolv.conf has no nameserver)"
  fi
  _rpt ""

  # ── DUT Interface ─────────────────────────────────────────────────────────
  local dut_verdict=""
  if [[ -n "$DUT_IFACE" ]]; then
    local dut_status="OK"
    local -a dut_evidence=()

    if [[ -n "$dut_carrier_changes" && "$dut_carrier_changes" =~ ^[0-9]+$ && \
          -n "$carrier_changes" && "$carrier_changes" =~ ^[0-9]+$ ]]; then
      if (( dut_carrier_changes > carrier_changes * 5 && dut_carrier_changes > 20 )); then
        dut_status="SUSPECT"
        dut_evidence+=("DUT carrier changes (${dut_carrier_changes}) >> host (${carrier_changes})")
      fi
    fi
    if [[ "${dut_speed:-}" == "Unknown!" || "${dut_speed:-}" == "Unknown" ]] && \
       [[ "${speed:-}" != "Unknown!" && "${speed:-}" != "Unknown" && -n "${speed:-}" ]]; then
      dut_status="SUSPECT"
      dut_evidence+=("DUT speed Unknown! while host speed is ${speed}")
    fi
    [[ "${dut_operstate:-}" == "down" || "${dut_operstate:-}" == "unknown" ]] && \
      dut_status="SUSPECT" && dut_evidence+=("DUT operstate=${dut_operstate:-}")

    local dut_col="$GREEN"
    [[ "$dut_status" == "SUSPECT" ]] && dut_col="$RED"
    _rpt "  DUT Interface (${DUT_IFACE} — device under test)"
    _rpt "    Status   : ${dut_col}${dut_status}${RESET}"
    local _cc_display="${dut_carrier_changes:-?}  vs host ${iface}: ${carrier_changes:-?}"
    _rpt "    Carrier changes: ${_cc_display}"
    _rpt "    Speed    : ${dut_speed:-unknown}  vs host ${iface}: ${speed:-unknown}"
    _rpt "    Link state: ${dut_operstate:-unknown}  vs host ${iface}: ${operstate:-unknown}"
    if [[ "${#dut_evidence[@]}" -gt 0 ]]; then
      _rpt "    Evidence : $(IFS='; '; echo "${dut_evidence[*]}")"
    fi
    _rpt ""
    [[ "$dut_status" == "SUSPECT" ]] && \
      dut_verdict="Fault is likely in the DUT or the DUT-host cable. Host interface (${iface}) is stable — the issue is not upstream of this computer."
  fi

  # ── Verdict ───────────────────────────────────────────────────────────────
  local vsep="  ──────────────────────────────────────────────────────────"
  local verdict=""
  if [[ -n "$dut_verdict" ]]; then
    verdict="$dut_verdict"
  elif [[ "$l1_status" == "SUSPECT" && "$l2drv_status" != "SUSPECT" && \
          "$l3_status" != "SUSPECT" ]]; then
    verdict="Fault is most likely in the PHYSICAL LAYER (cable, SFP, or switch port)."
  elif [[ "$l1_status" == "SUSPECT" && "$l2drv_status" == "SUSPECT" ]]; then
    verdict="Physical layer and driver both show issues — address physical first (replace cable/SFP), then check driver/firmware."
  elif [[ "$l1_status" != "SUSPECT" && "$l2drv_status" == "SUSPECT" ]]; then
    verdict="NIC DRIVER or firmware issue — physical layer appears OK. Update driver or firmware; check dmesg for reset events."
  elif [[ "$l3_status" == "SUSPECT" ]]; then
    verdict="GATEWAY/ROUTER unreachable — not a link-layer fault. Check the cable to the gateway and the gateway itself."
  elif [[ "$dns_status" == "SUSPECT" ]]; then
    verdict="DNS resolver issue — link is stable. Check /etc/resolv.conf and firewall rules for UDP port 53."
  elif [[ "$l1_status" == "OK" && "$l2drv_status" == "OK" && \
          "$l3_status" != "SUSPECT" && "$dns_status" != "SUSPECT" ]]; then
    verdict="No fault detected at any monitored layer. The flap may have been transient; monitor with: ./flap -i ${iface} -f 30"
  else
    verdict="Multiple or ambiguous indicators — investigate the PHYSICAL LAYER first (replace cable, try different switch port)."
  fi

  _rpt "$vsep"
  _rpt "  ${BOLD}VERDICT: ${verdict}${RESET}"
  _rpt "$vsep"
}
